import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const publicDir = join(__dirname, "..", "examples", "todo", "public");

mkdirSync(publicDir, { recursive: true });

const apiBase = process.env.FLEX_PUBLIC_API_URL ?? "";
const httpOnly = process.env.VERCEL === "1";

writeFileSync(
  join(publicDir, "config.js"),
  `// Generated by vercel-build — do not edit
window.FLEX_CONFIG = {
  apiBase: ${JSON.stringify(apiBase)},
  httpOnly: ${httpOnly},
  pollIntervalMs: 3000,
};
`,
  "utf8"
);

console.log("Vercel build: wrote public/config.js", { apiBase: apiBase || "(same origin)" });
