import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const publicDir = join(__dirname, "..", "examples", "todo", "public");

mkdirSync(publicDir, { recursive: true });

const apiBase = process.env.FLEX_PUBLIC_API_URL ?? "";
const httpOnly = process.env.VERCEL === "1";

const configPath = join(publicDir, "config.js");
const configContent = `// Generated by vercel-build — do not edit
window.FLEX_CONFIG = {
  apiBase: ${JSON.stringify(apiBase)},
  httpOnly: ${httpOnly},
  pollIntervalMs: 3000,
};
`;

// На Vercel — всегда пишем. Локально — только если явно задан FLEX_PUBLIC_API_URL,
// чтобы npm run build:vercel не портил git status на Windows.
if (process.env.VERCEL === "1" || process.env.FLEX_PUBLIC_API_URL) {
  writeFileSync(configPath, configContent, "utf8");
  console.log("Vercel build: wrote public/config.js", {
    apiBase: apiBase || "(same origin)",
  });
} else {
  console.log("Vercel build: config.js не трогаем (локальная сборка)");
}
