import { writeFileSync, mkdirSync, cpSync, rmSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const publicDir = join(root, "examples", "todo", "public");
const todoDest = join(root, "api", "_lib", "todo");
const todoSrc = join(root, "examples", "todo", "src");

mkdirSync(publicDir, { recursive: true });

rmSync(todoDest, { recursive: true, force: true });
cpSync(todoSrc, todoDest, { recursive: true });
console.log("Vercel build: copied examples/todo/src -> api/_lib/todo");

const apiBase = process.env.FLEX_PUBLIC_API_URL ?? "";
const httpOnly = process.env.VERCEL === "1";

const configPath = join(publicDir, "config.js");
const configContent = `// Generated by vercel-build — do not edit
window.FLEX_CONFIG = {
  apiBase: ${JSON.stringify(apiBase)},
  httpOnly: ${httpOnly},
  pollIntervalMs: 3000,
  fetchTimeoutMs: 45000,
};
`;

// На Vercel — всегда пишем. Локально — только если явно задан FLEX_PUBLIC_API_URL,
// чтобы npm run build:vercel не портил git status на Windows.
if (process.env.VERCEL === "1" || process.env.FLEX_PUBLIC_API_URL) {
  writeFileSync(configPath, configContent, "utf8");
  console.log("Vercel build: wrote public/config.js", {
    apiBase: apiBase || "(same origin)",
  });
} else {
  console.log("Vercel build: config.js не трогаем (локальная сборка)");
}
